# Energy Intensities
## Passenger per vkm
```{r}
items <- c(
          "Energy intensity|Transport|Bunkers|Pass|International Aviation",
          "Energy intensity|Transport|Pass|Rail",
          "Energy intensity|Transport|Pass|Domestic Aviation",
          "Energy intensity|Transport|Pass|Road",
          "Energy intensity|Transport|Pass|Road|LDV",
          "Energy intensity|Transport|Pass|Road|LDV|Four Wheelers",
          "Energy intensity|Transport|Pass|Road|LDV|Three Wheelers",
          "Energy intensity|Transport|Pass|Road|LDV|Two Wheelers",
          "Energy intensity|Transport|Pass|Road|Bus"
  )
walk(items, showLinePlots, data = data, scales = "fixed")
```

## Freight per vkm
```{r}
items <- c(
            "Energy intensity|Transport|Bunkers|Freight|International Shipping",
            "Energy intensity|Transport|Freight|Domestic Shipping",
            "Energy intensity|Transport|Freight|Rail",
            "Energy intensity|Transport|Freight|Road"
  )
walk(items, showLinePlots, data = data, scales = "fixed")
```

## Truck sizes per tkm
```{r}
items <- c(
            "Energy intensity per p/tkm|Transport|Freight|Road|Light|Truck (0-3_5t)",
            "Energy intensity per p/tkm|Transport|Freight|Road|Light|Truck (7_5t)",
            "Energy intensity per p/tkm|Transport|Freight|Road|Heavy|Truck (18t)",
            "Energy intensity per p/tkm|Transport|Freight|Road|Heavy|Truck (26t)",
            "Energy intensity per p/tkm|Transport|Freight|Road|Heavy|Truck (40t)"
  )
showMultiLinePlots(data, items, scales = "fixed", nrowNum = 2)
```
